"""first setup

Revision ID: 75b00e4a4c85
Revises: 
Create Date: 2020-09-06 22:20:34.590265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b00e4a4c85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equip_amount', sa.Integer(), nullable=True),
    sa.Column('rent_period', sa.Integer(), nullable=True),
    sa.Column('downpayment', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('flat_rate', sa.Float(), nullable=True),
    sa.Column('payment_type', sa.Text(), nullable=True),
    sa.Column('payment_period', sa.Text(), nullable=True),
    sa.Column('irr_nor', sa.Float(), nullable=True),
    sa.Column('irr_exp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('user_dep', sa.String(length=20), nullable=True),
    sa.Column('user_level', sa.String(length=20), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('blogposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tra_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('cashflow_nature', sa.String(length=64), nullable=True),
    sa.Column('cashflow_type', sa.Integer(), nullable=True),
    sa.Column('cashflow_amount', sa.Integer(), nullable=True),
    sa.Column('cashflow_tax', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tra_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashflows')
    op.drop_table('blogposts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trades')
    # ### end Alembic commands ###
